name: config-dotnet-webConfig
filetype: config$
target: file
category: Config
type: simple-text
advice: Upgrade to .Net Core
effort: 0
readiness: 0
criticality: 50:50
tags:
- value: web-config
patterns:
- value: web.config
- value: Web.config
