#qc1
name: config-sessionState-xpath
filetype: config$
target: file
type: xpath
advice: App should be executed as a stateless process
readiness: 2
effort: 200
category: stateful
tags:
  - value: stateful
  - value: TAS
patterns:
  - value: /configuration/system.web/sessionState[@mode="InProc" or @mode="StateServer"][1]
