name: java-system-config
ruletype: standard
filetype: $
target: line
type: regex
defaultpattern: (System.)%s\(
advice: Review usage of environment variables and system properties and externalize.
effort: 3
readiness: 10 
category: config
tags:
- value: config
patterns:
- value: getenv
- value: getProperty
- value: setProperty
- value: setProperties
profiles:
- value: cloud-suitability