name: java-security
filetype: java$
target: line
type: contains
advice:
recipes:
effort: 10
readiness: 0
category: security
tags: 
- value: security
patterns:
- value: javax.net.ssl.keyStore
  tag: javax-net-ssl
- value: javax.net.ssl.keyStoreType
  tag: javax-net-ssl
- value: javax.net.ssl.keyStorePassword
  tag: javax-net-ssl
- value: javax.net.ssl.trustStore
  tag: javax-net-ssl
- value: javax.net.ssl.trustStoreType
  tag: javax-net-ssl
- value: javax.net.ssl.trustStorePassword
  tag: javax-net-ssl
- value: java.security
  tag: x509
