name: java-system-config
filetype: $
target: line
type: contains
advice: Review usage of environment variables and system properties and externalize.
effort: 3
readiness: 10 
category: env-config
tags:
- value: env-config
patterns:
- value: System.getenv(
- value: System.getProperty(
- value: System.setProperty(
