#SW
name: java-transportSecurity
filetype: java$
target: line
type: contains
category: Security
advice: Not compatable with TAS, change to TransportSecurity.NONE or move to TKG
effort: 10
readiness: 10
tags:
  - value: api
  - value: transportSecurity
  - value: security-guarantee
patterns:
  - value: TransportGuarantee.CONFIDENTIAL
##TransportGuarantee.CONFIDENTIAL
