name: weblogic-cluster-config
ruletype: fire-once
filetype: conf$
target: line
type: regex
defaultpattern: "^%s.*"
category: wlcluster
advice: Weblogic clusters cannot run in K8S
effort: 1
readiness: 0
tags:
  - value: wl-cluster
patterns:
  #--- cluster property
  - value: WebLogicCluster
profiles:
- value: cloud-suitability