#SW
name: xml-transportSecurity
filetype: xml$
target: line
type: contains
category: security
advice: Change to NONE
effort: 2
readiness: 10
tags:
- value: security
- value: webapp
patterns:
- value: <transport-guarantee>CONFIDENTIAL
##<transport-guarantee>CONFIDENTIAL
